"""
HTML reporter implementation.
Generates interactive HTML reports with charts.
"""
from datetime import datetime
from pathlib import Path
from typing import Dict, Any
import json

from .base_reporter import BaseReporter
from ..models.validation_result import ValidationSummary, ValidationResult
from ..models.enums import ReporterType, ValidationStatus


class HTMLReporter(BaseReporter):
    """Generates HTML format reports with charts."""

    def get_reporter_type(self) -> ReporterType:
        """Return reporter type."""
        return ReporterType.HTML

    def generate_report(self, summary: ValidationSummary) -> str:
        """
        Generate HTML report from validation summary.

        Args:
            summary: ValidationSummary with all results

        Returns:
            Path to generated HTML file
        """
        # Prepare output path
        if not self.output_path:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            self.output_path = f"output/reports/validation_report_{timestamp}.html"

        self._ensure_output_directory()

        # Get configuration
        include_charts = self.config.get('include_charts', True)
        show_passed_details = self.config.get('show_passed_details', False)
        template_path = self.config.get('template')

        # Generate HTML content
        if template_path and Path(template_path).exists():
            html_content = self._generate_from_template(summary, template_path)
        else:
            html_content = self._generate_html(summary, include_charts, show_passed_details)

        # Write HTML file
        output_file = Path(self.output_path)
        with open(output_file, 'w') as f:
            f.write(html_content)

        self.logger.info(f"HTML report generated: {output_file}")
        return str(output_file)

    def _generate_html(self, summary: ValidationSummary,
                      include_charts: bool, show_passed: bool) -> str:
        """Generate HTML content."""
        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Validation Report - {summary.start_time.strftime('%Y-%m-%d')}</title>
    <style>
        {self._get_css()}
    </style>
    {self._get_plotly_script() if include_charts else ''}
</head>
<body>
    <div class="container">
        <header>
            <h1>Validation Report</h1>
            <p class="subtitle">Generated on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
        </header>

        {self._generate_summary_section(summary)}

        {self._generate_charts(summary) if include_charts else ''}

        {self._generate_results_section(summary, show_passed)}

        <footer>
            <p>Generated by Validation Framework</p>
        </footer>
    </div>

    {self._get_charts_script(summary) if include_charts else ''}
</body>
</html>
"""
        return html

    def _generate_from_template(self, summary: ValidationSummary,
                               template_path: str) -> str:
        """Generate HTML from Jinja2 template."""
        try:
            from jinja2 import Template

            with open(template_path, 'r') as f:
                template = Template(f.read())

            return template.render(
                summary=summary,
                datetime=datetime,
                ValidationStatus=ValidationStatus
            )
        except ImportError:
            self.logger.warning("Jinja2 not installed, using built-in template")
            return self._generate_html(summary, True, False)

    def _generate_summary_section(self, summary: ValidationSummary) -> str:
        """Generate summary section HTML."""
        status_class = 'success' if not summary.has_failures() else 'failure'

        return f"""
        <section class="summary {status_class}">
            <h2>Summary</h2>
            <div class="summary-grid">
                <div class="summary-item">
                    <div class="summary-label">Total Validations</div>
                    <div class="summary-value">{summary.total_validations}</div>
                </div>
                <div class="summary-item success">
                    <div class="summary-label">Passed</div>
                    <div class="summary-value">{summary.passed}</div>
                </div>
                <div class="summary-item warning">
                    <div class="summary-label">Warnings</div>
                    <div class="summary-value">{summary.warnings}</div>
                </div>
                <div class="summary-item failure">
                    <div class="summary-label">Failed</div>
                    <div class="summary-value">{summary.failed}</div>
                </div>
                <div class="summary-item error">
                    <div class="summary-label">Errors</div>
                    <div class="summary-value">{summary.errors}</div>
                </div>
                <div class="summary-item">
                    <div class="summary-label">Success Rate</div>
                    <div class="summary-value">{summary.success_rate:.1f}%</div>
                </div>
                <div class="summary-item">
                    <div class="summary-label">Duration</div>
                    <div class="summary-value">{summary.total_execution_time_seconds:.2f}s</div>
                </div>
            </div>
        </section>
        """

    def _generate_charts(self, summary: ValidationSummary) -> str:
        """Generate charts section."""
        return """
        <section class="charts">
            <h2>Visualizations</h2>
            <div class="chart-container">
                <div id="statusChart" class="chart"></div>
                <div id="typeChart" class="chart"></div>
            </div>
        </section>
        """

    def _generate_results_section(self, summary: ValidationSummary,
                                 show_passed: bool) -> str:
        """Generate individual results section."""
        results_html = '<section class="results"><h2>Validation Results</h2>'

        for result in summary.results:
            if not show_passed and result.status == ValidationStatus.PASSED:
                continue

            results_html += self._generate_result_card(result)

        results_html += '</section>'
        return results_html

    def _generate_result_card(self, result: ValidationResult) -> str:
        """Generate HTML card for a single result."""
        status_class = result.status.value.lower()
        icon = self._get_status_icon(result.status)

        card = f"""
        <div class="result-card {status_class}">
            <div class="result-header">
                <h3>{icon} {result.name}</h3>
                <span class="badge {status_class}">{result.status.value}</span>
            </div>
            <div class="result-details">
                <p><strong>Type:</strong> {result.validation_type.value}</p>
                <p><strong>Duration:</strong> {result.execution_time_seconds:.2f}s</p>
                <p><strong>Source:</strong> {result.source_name}</p>
                <p><strong>Target:</strong> {result.target_name}</p>
        """

        # Add type-specific details
        if result.source_count is not None:
            card += f"<p><strong>Source Count:</strong> {result.source_count:,}</p>"
        if result.target_count is not None:
            card += f"<p><strong>Target Count:</strong> {result.target_count:,}</p>"
        if result.difference is not None:
            card += f"<p><strong>Difference:</strong> {result.difference:,} ({result.difference_percent:.2f}%)</p>"

        if result.error_message:
            card += f'<p class="error"><strong>Error:</strong> {result.error_message}</p>'

        card += """
            </div>
        </div>
        """

        return card

    def _get_charts_script(self, summary: ValidationSummary) -> str:
        """Generate JavaScript for charts."""
        # Prepare data for charts
        status_data = {
            'Passed': summary.passed,
            'Warnings': summary.warnings,
            'Failed': summary.failed,
            'Errors': summary.errors
        }

        # Count by validation type
        type_counts = {}
        for result in summary.results:
            vtype = result.validation_type.value
            type_counts[vtype] = type_counts.get(vtype, 0) + 1

        return f"""
        <script>
            // Status distribution chart
            var statusData = [{
                values: {json.dumps(list(status_data.values()))},
                labels: {json.dumps(list(status_data.keys()))},
                type: 'pie',
                marker: {{
                    colors: ['#28a745', '#ffc107', '#dc3545', '#dc3545']
                }}
            }}];

            var statusLayout = {{
                title: 'Validation Status Distribution',
                height: 400
            }};

            Plotly.newPlot('statusChart', statusData, statusLayout);

            // Validation type chart
            var typeData = [{
                x: {json.dumps(list(type_counts.keys()))},
                y: {json.dumps(list(type_counts.values()))},
                type: 'bar',
                marker: {{
                    color: '#007bff'
                }}
            }}];

            var typeLayout = {{
                title: 'Validations by Type',
                xaxis: {{ title: 'Validation Type' }},
                yaxis: {{ title: 'Count' }},
                height: 400
            }};

            Plotly.newPlot('typeChart', typeData, typeLayout);
        </script>
        """

    def _get_status_icon(self, status: ValidationStatus) -> str:
        """Get icon for status."""
        icons = {
            ValidationStatus.PASSED: '✓',
            ValidationStatus.FAILED: '✗',
            ValidationStatus.WARNING: '⚠',
            ValidationStatus.ERROR: '✗',
            ValidationStatus.SKIPPED: '○'
        }
        return icons.get(status, '?')

    def _get_plotly_script(self) -> str:
        """Get Plotly CDN script tag."""
        return '<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>'

    def _get_css(self) -> str:
        """Get CSS styles."""
        return """
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif;
            line-height: 1.6;
            color: #333;
            background-color: #f5f5f5;
        }

        .container {
            max-width: 1200px;
            margin: 0 auto;
            padding: 20px;
        }

        header {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 40px;
            border-radius: 10px;
            margin-bottom: 30px;
            text-align: center;
        }

        header h1 {
            font-size: 2.5em;
            margin-bottom: 10px;
        }

        .subtitle {
            opacity: 0.9;
        }

        section {
            background: white;
            padding: 30px;
            margin-bottom: 30px;
            border-radius: 10px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }

        h2 {
            color: #667eea;
            margin-bottom: 20px;
            border-bottom: 2px solid #f0f0f0;
            padding-bottom: 10px;
        }

        .summary-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
            gap: 20px;
            margin-top: 20px;
        }

        .summary-item {
            text-align: center;
            padding: 20px;
            border-radius: 8px;
            background: #f8f9fa;
        }

        .summary-label {
            font-size: 0.9em;
            color: #666;
            margin-bottom: 10px;
        }

        .summary-value {
            font-size: 2em;
            font-weight: bold;
            color: #333;
        }

        .summary-item.success { background: #d4edda; }
        .summary-item.warning { background: #fff3cd; }
        .summary-item.failure { background: #f8d7da; }
        .summary-item.error { background: #f8d7da; }

        .chart-container {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(400px, 1fr));
            gap: 20px;
        }

        .chart {
            min-height: 400px;
        }

        .result-card {
            border: 1px solid #ddd;
            border-radius: 8px;
            padding: 20px;
            margin-bottom: 20px;
            border-left: 4px solid #007bff;
        }

        .result-card.passed { border-left-color: #28a745; }
        .result-card.failed { border-left-color: #dc3545; }
        .result-card.warning { border-left-color: #ffc107; }
        .result-card.error { border-left-color: #dc3545; }

        .result-header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 15px;
        }

        .result-header h3 {
            margin: 0;
            color: #333;
        }

        .badge {
            padding: 5px 15px;
            border-radius: 20px;
            font-size: 0.85em;
            font-weight: bold;
            text-transform: uppercase;
        }

        .badge.passed { background: #28a745; color: white; }
        .badge.failed { background: #dc3545; color: white; }
        .badge.warning { background: #ffc107; color: #333; }
        .badge.error { background: #dc3545; color: white; }

        .result-details p {
            margin: 8px 0;
        }

        .result-details .error {
            color: #dc3545;
            font-weight: bold;
        }

        footer {
            text-align: center;
            color: #666;
            padding: 20px;
        }
        """
